# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 789911c4df6f57628901f1e3c0a5089b62dd05f5eed580112c2e97edfa5e85cc48826e2f164e663ad779064835390e23a206f65260baa93ed200b028622516df

test:
  secret_key_base: 1dddf9e9bb6ac1fb6a5455f6d78f59aeab6695c6454c6930fad23e456098ac5007a183333fe61644e357bac56f57a54a2be5fe61c1346c4e85230b47e7a8001e

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
